### PR TITLE
Remove quote preference in Ruby

### PR DESCRIPTION
**Pull request by zpengyu**
As discussed in the office today, it seems like no one like this any more.

### CODE REVIEW

**Comment by Koronen** [comment]
I don't care much about single vs. double quotes, but I think we should keep this rule in order to stay consistent.

**Comment by Koronen** [comment]
Ping @studentcompetitions/developers

**Comment by juliafanny** [comment]
I have no opinion in this

**Comment by Frost** [comment]
I really prefer double-quotes over single-quotes, so I'm all for removing this rule.

**Comment by vacker** [comment]
I usually use single quotes for strings and double only for interpolation and so on.

**Comment by nerf** [comment]
double-quotes to rule them all! :+1:

**Comment by zpengyu** [comment]
How about now:  @studentcompetitions/developers 

`Prefer double quotes for strings.`

The idea is double quote works in all situations and won't have any performance issues.
http://stackoverflow.com/questions/1836467/is-there-a-performance-gain-in-using-single-quotes-vs-double-quotes-in-ruby

**Comment by Koronen** [comment]
LGTM! :+1:

**Comment by vacker** [comment]
Always use double quotes is more convenient for sure.

**Pull request merged**
