### PR TITLE
Allow for alignment

### PR DESCRIPTION
**Pull request by Koronen**
This will allow us to use extra spacing for alignment of tokens.

Ref: <https://github.com/studentcompetitions/sqore/pull/1077>

### CODE REVIEW

**Comment by Frost** [comment]
I agree with this. Also, the wording on is a bit weird, because the alinging is actually horizontal, right?

:+1:

**Comment by maxnordlund** [comment]
:+1: on this. Don't know if it can handle some sort of vertical alignment, but not sure how to word it differently.

**Comment by Koronen** [comment]
I don't have a strong opinion on this.

/cc @sievan @maxnordlund @juliafanny @SteveLTN

**Comment by SteveLTN** [comment]
I totally agree. I'm not a super fan of alignment, but there are certain cases where aligning a token vertically makes the code easier to read.

**Comment by sievan** [comment]
This can be great for readability, so: :+1:

**Comment by Koronen** [comment]
A majority of the development team are either in favor or indifferent. Merging.

**Pull request merged**
