### PR TITLE
Remove preference for CoffeeScript English operators

### PR DESCRIPTION
**Pull request by Koronen**
I've noticed lately that we don't really follow these rules, so I think we should remove them. Sticking to the "regular" operators is also good considering our planned migration from CoffeeScript to ES6.

### CODE REVIEW

**Comment by Frost** [comment]
:+1:

**Comment by Frost** [comment]
I think it's a sane thing to use the "regular" operators, especially since we also write so much ruby code, and in ruby `and` and `&&` have a pretty significant semantics, since they have different preference (see [this gist](https://gist.github.com/Frost/4951876) for an example).

**Comment by chav02** [comment]
:+1:

**Comment by sievan** [comment]
:+1:

**Comment by Koronen** [comment]
Still quite few replies, but it's been more than a week now, so merging.

**Pull request merged**
