### PR TITLE
Add requirement to suffix dangerous methods with "!".

### PR DESCRIPTION
**Pull request by tsikov**
I don't have strong opinion about this, but nevertheless I think it is a nice convention. Predicates are with "?" and "dangerous methods" - with "!". What do you guys think?

### CODE REVIEW

**Comment by Koronen** [comment]
I'm :-1: on this. I think the "base name" of the method (maybe together with the name of the class and/or name of the variable holding an instance of the object) should make it clear that it mutates state, so a `!` shouldn't be necessary.

**Comment by maxnordlund** [comment]
I don't want to limit the use of `!` to just mutating state, and feel that this would do that. However if we have two methods that does the same thing, and only differ in mutating vs. returning then `!` is a nice way to separate them. This is comes from `Array`/`Hash`/... that does this.

**Comment by chav02** [comment]
There's two conventions for the usage of ! already, and I don't think we should add to that confusion.

Right now, in basic ruby, ! denotes a method that does the same as another method, but modifies the object it's called upon.

Additionally ! can also denote a method that will throw an exception instead of returning nil, like activerecords save vs save!.

I don't think  I've seen ! used on methods that do not have a basic variant, and I don't think we should start.

**Comment by tsikov** [comment]
OK guys, I am closing this :+1:

**Pull request closed without merging**
